language: c
os:
- linux
compiler:
  - gcc
  - clang
script: extras/build-tests/nix/build $BUILDCONFIG
env:
  - BUILDCONFIG=""
  - BUILDCONFIG="system-cares"
  - BUILDCONFIG="system-cares system-curl"
  - BUILDCONFIG="local-curl"
matrix:
  include:
  - os: osx
    compiler: clang
    BUILDCONFIG=""
  - os: osx
    compiler: clang
    BUILDCONFIG="system-cares"
  - os: osx
    compiler: clang
    BUILDCONFIG="system-cares system-curl"
  - os: osx
    compiler: clang
    BUILDCONFIG="local-curl"
  - env: BUILDCONFIG="libressl-25"
  - env: BUILDCONFIG="libressl-26"
  - env: BUILDCONFIG="libressl-27"
  - env: BUILDCONFIG="openssl-102"
  - env: BUILDCONFIG="openssl-110"
  - env: BUILDCONFIG="openssl-111"
