language: c
os:
- linux
- osx
compiler:
  - gcc
  - clang
script: extras/build-tests/nix/build $BUILDCONFIG
env:
  - BUILDCONFIG=""
  - BUILDCONFIG="system-cares"
  - BUILDCONFIG="system-cares system-curl"
  - BUILDCONFIG="local-curl"
  - BUILDCONFIG="libressl-25"
  - BUILDCONFIG="libressl-26"
  - BUILDCONFIG="libressl-27"
  - BUILDCONFIG="openssl-102"
  - BUILDCONFIG="openssl-110"
  - BUILDCONFIG="openssl-111"
